master:
  driver: ros2_canopen::MasterDriver
  node_id: 9
  package: canopen_master_driver
  start_nodes: false
  sync_period: 10000
options:
  dcf_path: '@BUS_CONFIG_PATH@'
panda_joint1:
  dcf: KincoCMDriver.eds
  driver: ros2_canopen::Cia402Driver
  heartbeat_producer: 1000
  node_id: 1
  package: canopen_402_driver
  period: 10
  position_mode: 1
  rpdo: &id001
    1:
      cob_id: auto
      enabled: true
      mapping:
      - index: 24640
        sub_index: 0
      - index: 24672
        sub_index: 0
    2:
      cob_id: auto
      enabled: true
      mapping:
      - index: 24698
        sub_index: 0
      - index: 24831
        sub_index: 0
    3:
      enabled: false
    4:
      enabled: false
  sdo: &id002
  - index: 24705
    sub_index: 0
    value: 1000
  - index: 24707
    sub_index: 0
    value: 10000
  - index: 24708
    sub_index: 0
    value: 10000
  - index: 24709
    sub_index: 0
    value: 10000
  - index: 24728
    sub_index: 0
    value: 0
  tpdo: &id003
    1:
      cob_id: auto
      enabled: true
      mapping:
      - index: 24641
        sub_index: 0
      - index: 24673
        sub_index: 0
      transmission: 1
    2:
      cob_id: auto
      enabled: true
      mapping:
      - index: 24684
        sub_index: 0
      transmission: 1
    3:
      enabled: false
    4:
      enabled: false
panda_joint2:
  dcf: KincoCMDriver.eds
  driver: ros2_canopen::Cia402Driver
  heartbeat_producer: 1000
  node_id: 2
  package: canopen_402_driver
  period: 10
  position_mode: 1
  rpdo: *id001
  sdo: *id002
  tpdo: *id003
panda_joint3:
  dcf: KincoCMDriver.eds
  driver: ros2_canopen::Cia402Driver
  heartbeat_producer: 1000
  node_id: 4
  package: canopen_402_driver
  period: 10
  position_mode: 1
  rpdo: *id001
  sdo: *id002
  tpdo: *id003
panda_joint4:
  dcf: KincoCMDriver.eds
  driver: ros2_canopen::Cia402Driver
  heartbeat_producer: 1000
  node_id: 5
  package: canopen_402_driver
  period: 10
  position_mode: 1
  rpdo: *id001
  sdo: *id002
  tpdo: *id003
panda_joint5:
  dcf: KincoCMDriver.eds
  driver: ros2_canopen::Cia402Driver
  heartbeat_producer: 1000
  node_id: 6
  package: canopen_402_driver
  period: 10
  position_mode: 1
  rpdo: *id001
  sdo: *id002
  tpdo: *id003
panda_joint6:
  dcf: KincoCMDriver.eds
  driver: ros2_canopen::Cia402Driver
  heartbeat_producer: 1000
  node_id: 7
  package: canopen_402_driver
  period: 10
  position_mode: 1
  rpdo: *id001
  sdo: *id002
  tpdo: *id003
panda_joint7:
  dcf: KincoCMDriver.eds
  driver: ros2_canopen::Cia402Driver
  heartbeat_producer: 1000
  node_id: 8
  package: canopen_402_driver
  period: 10
  position_mode: 1
  rpdo: *id001
  sdo: *id002
  tpdo: *id003
